Readazione del Glossario
SevenBitsSwe/7BitsDocs pull request #34
Opened 2024-11-14 13:38 UTC by CodeUncas

2024-11-14 14:20 UTC, federicopivetta commented
@CodeUncas ho verificato ogni aggiunta corrispondente alla versione 0.2.1 e sono corrette

2024-11-14 16:42 UTC, federicopivetta commented
La versione del glossario 0.2.2 aggiunge i termini : Branch; Merge; PR; Milestone; Issue e Baseline

2024-11-21 09:42 UTC, federicopivetta commented
La versione del glossario 0.2.3 aggiunge i termini : IA e LLM

2024-12-10 13:08 UTC, federicopivetta commented
La versione del glossario 0.2.5 aggiunge i termini : Feedback, Framework e Proponente

2024-12-11 16:09 UTC, Sadixo requested changes
@Meja04 Rivedere il termine Protocollo togliendo la frase iniziale "In Informatica", essendo scontato che stiamo parlando del termine informatico. Però l'esempio riportato non descrive bene la parola per come la utilizza il prof. 
Il resto apposto.

2024-12-15 15:05 UTC, Sadixo approved these changes

2025-01-04 11:29 UTC, riky869 requested changes

2025-01-04 11:29 UTC, riky869 commented on RTB/Glossario.tex
> +RTB & Acronimo di "Requirement and Technology Retrospective", è la prima revisione di avanzamento del progetto didattico. Fissa i requisiti da soddisfare in accordo con il proponente; motiva le tecno
L'acronimo è Requirements and Technology Baseline

2025-01-04 11:29 UTC, riky869 commented on RTB/Glossario.tex
> +Python & Linguaggio di programmazione ad alto livello, versatile e orientato agli oggetti. Grazie alla sua sintassi semplice viene utilizzato in una vasta gamma di applicazioni, tra cui sviluppo soft
Linguaggio di programmazione ad alto livello, semplice e versatile. Supporta più paradigmi di programmazione, tra cui quello ad oggetti e quello funzionale.

2025-01-04 11:29 UTC, riky869 commented on RTB/Glossario.tex
> +Pull Request & Richiesta da parte di un membro del team, solitamente effettuata tramite una piattaforma di hosting come GitHub per integrare le modifiche fatte in un branch nel repository principale.
al posto di "una piattaforma di hosting come GitHub", userei solo "una piattaforma come GitHub"

2025-01-13 16:45 UTC, CodeUncas commented on RTB/Glossario.tex
> +Walkthrough & Tecnica di verifica di un documento o di un codice in modo approfondito e senza l'uso di una checklist predefinita. Durante questa revisione, l'attenzione è focalizzata sul contenuto pe
```suggestion
Walkthrough & Tecnica di verifica di un documento o di un codice in modo approfondito e senza ricorrere a una checklist predefinita. Durante questa revisione, l'attenzione è focalizzata sul contenuto per individuare e correggere errori, evidenziando aspetti critici e identificando potenziali problematiche, senza aderire a parametri di valutazione rigidi.\\
```

2025-01-13 16:47 UTC, CodeUncas commented on RTB/Glossario.tex
> +Inspection & Tecnica di analisi statica utilizzata per individuare errori attraverso una lettura mirata. Durante l'inspection, il verificatore segue una sequenza di passaggi prestabiliti per garantir
```suggestion
Inspection & Tecnica di analisi statica utilizzata per individuare errori attraverso una lettura mirata. Durante l'inspection, il verificatore segue una sequenza di passaggi prestabiliti per assicurare il rispetto delle regole definite nel Piano di Qualifica, garantendo la conformità agli standard e la qualità del prodotto.\\
```

2025-01-13 16:49 UTC, CodeUncas commented
@Meja04 verificato, vedi suggestion

2025-02-21 08:53 UTC, Sadixo approved these changes

2025-02-21 13:05 UTC, CodeUncas reviewed
Verificato 21/04/2025

2025-02-21 13:07 UTC, riky869 approved these changes
Approvo correttezza documento

2025-02-21 13:14 UTC, merged