Redazione iniziale documento analisi dei requisiti
SevenBitsSwe/7BitsDocs pull request #37
Opened 2024-11-15 15:09 UTC by CodeUncas

Redazione sezione 1 e sezione 2, issue #36

2024-11-15 15:10 UTC, CodeUncas commented
@riky869  attendo verifica del documento in versione 0.1.1, fammi sapere se c'è qualche modifica e/o correzione

2024-11-15 15:49 UTC, riky869 commented
Al punto 2.3.1.2 parola "constesto" e poco sotto "accedibile" non esiste puoi cambiarla in accessibile.
Per il resto correto ma da rivedere dopo incontro con azienda del 2024-20-11

2024-11-22 12:02 UTC, CodeUncas commented
@federicopivetta richiesta verifica per i primi due casi d'uso

2024-11-23 09:01 UTC, federicopivetta commented
@CodeUncas ho verificato i primi casi d'uso e sono corretti, volevo anche segnalarti che le tue modifiche alla sezione 4 e 5 non sono presenti nel Registro modifiche. Nella sezione 4.2 alla descrizione del RQ01 penso sia da correggere la ripetizione della parola "analisi"

2024-11-23 13:05 UTC, CodeUncas commented
@federicopivetta perfetto , sistemo il registro, i casi d'uso , aggiungo qualche requisito e ti aggiorno per la nuova verifica

2024-11-24 16:31 UTC, federicopivetta commented
@Sadixo ho verificato UC1.2, UC2, RF02 e RF03, per quanto riguarda UC1.2 non è molto chiaro come l'utente privilegiato visualizzi gli annunci sulla mappa, ovvero se li vede collegati ai marker oppure no

2024-11-24 17:45 UTC, CodeUncas commented
@Sadixo ho aggiornato con le immagini nuove gli use cases , utilizzando il template linkato , (ricordarsi di rifare la pull)

2024-11-26 08:50 UTC, federicopivetta commented
@Aniysi ho verificato, c'è solo 1 errore nella figura 1 poiché l'attore inserito per gli use case 3.1 e 3.2 è Utente ma dovrebbe essere Utente Privilegiato

2024-11-28 10:32 UTC, federicopivetta commented
@Aniysi ho messo te come verificatore, se riesci a caricare l'immagine degli use case UC3 - UC4 mettendo la P di privilegiato in maiuscolo cosi non ci sono discrepanze tra le immagini dei vari use case

2024-11-29 09:00 UTC, CodeUncas commented
@Aniysi ho aggiunto anchio qualche modifica aggiungendo il caso d'uso con attore il sensore , e aggiornando le varie tabelle dei requisiti, verifica il tutto insieme grazie.

2025-01-06 11:17 UTC, CodeUncas commented
@riky869 ti ho messo come verificatore, ho aggiunto tutta la parte che mancava per chiudere le issue

2025-01-06 21:19 UTC, riky869 submitted a review, later dismissed

2025-01-06 21:19 UTC, riky869 commented on RTB/Analisi_dei_Requisiti.tex
> +        \item Il LLM riceve i dati di posizione dall'utente e invia una richiesta al database statico per ottenere l'elenco dei POI nelle vicinanze dell'utente, con informazioni pertinenti come tipo
"Il LLM" non suona corretto. Credo che la versione corretta sia "L'LLM"

2025-01-06 21:19 UTC, riky869 commented on RTB/Analisi_dei_Requisiti.tex
> +        \item Il LLM utilizza i dati di posizione per filtrare i POI che si trovano in un raggio geografico predefinito. Il LLM applica inoltre un filtro basato su altre variabili, come le preferenze
"Il LLM" non suona corretto. Credo che la versione corretta sia "L'LLM"

2025-01-06 21:19 UTC, riky869 commented on RTB/Analisi_dei_Requisiti.tex
> +        \item Il LLM ha selezionato il punto di interesse più adeguato per l'utente in base alla posizione in tempo reale e il profilo.
"Il LLM" non suona corretto. Credo che la versione corretta sia "L'LLM"

2025-01-06 21:19 UTC, riky869 commented on RTB/Analisi_dei_Requisiti.tex
> +        \item Il LLM utilizza tutti i dettagli del PoI e del profilo utente per generare un annuncio testuale personalizzato. L'annuncio sarà proposto all'utente durante il percorso con il mezzo quin
"Il LLM" non suona corretto. Credo che la versione corretta sia "L'LLM"

2025-01-06 21:19 UTC, riky869 commented on RTB/Analisi_dei_Requisiti.tex
> +        \item Il LLM non ha selezionato il punto di interesse più adeguato per l'utente in base alla posizione in tempo reale e il profilo.
"Il LLM" non suona corretto. Credo che la versione corretta sia "L'LLM"

2025-01-06 21:19 UTC, riky869 commented on RTB/Analisi_dei_Requisiti.tex
> +        \item Il LLM omette per l'ultima rilevazione GPS, la generazione di un messaggio pubblicitario per l'utente
"Il LLM" non suona corretto. Credo che la versione corretta sia "L'LLM"

2025-01-08 08:37 UTC, Sadixo commented on RTB/Analisi_dei_Requisiti.tex
> +\label{UC1.2}
```suggestion
\label{UC1.3}
```

2025-01-08 08:38 UTC, Sadixo commented on RTB/Analisi_dei_Requisiti.tex
> +\label{UC1.3}
```suggestion
\label{UC1.2}
```

2025-01-08 09:00 UTC, Sadixo requested changes
Da correggere piccole cose, riguardanti di più alcune label di cui non sono stati cambiati i numeri in quelli adeguati. Per esempio UC1.2 e 1.3

2025-01-08 09:00 UTC, Sadixo commented on RTB/Analisi_dei_Requisiti.tex
> +\label{UC1.3}
```suggestion
\label{UC1.2}
```

2025-01-08 09:00 UTC, Sadixo commented on RTB/Analisi_dei_Requisiti.tex
> +\label{UC1.2}
```suggestion
\label{UC1.3}
```

2025-01-08 09:00 UTC, Sadixo commented on RTB/Analisi_dei_Requisiti.tex
> +            \item L'utente privilegiato seleziona un marker di uno determinato percoso per vederne la Dashboard$_G$ specifica;
```suggestion
            \item L'utente privilegiato seleziona un marker di un determinato percorso per visualizzarne la Dashboard$_G$ specifica;
```
Da valutare se inserire "visualizzarne" o lasciare "vedere". Secondo me entrambi sono corretti

2025-01-08 09:00 UTC, Sadixo commented on RTB/Analisi_dei_Requisiti.tex
> + \label{UC1.3.2}
```suggestion
 \label{UC1.2.2}
```

2025-01-08 09:00 UTC, Sadixo commented on RTB/Analisi_dei_Requisiti.tex
> +        \item Sistema di Processing
```suggestion
        \item Database
        \item Sistema di Stream Processing
```
Attenzione ad utilizzare sempre gli stessi nomi quando facciamo documenti ufficiali. La ridondanza è importante per far capire come chiamiamo un attore

2025-01-08 09:01 UTC, Sadixo commented on RTB/Analisi_dei_Requisiti.tex
> +        \item Sistema di Processing
O senò usa sempre Static Database e Sistema di Processing. Indifferente, basta che utilizziamo una nomenclatura unica

2025-01-10 10:50 UTC, federicopivetta commented on RTB/Analisi_dei_Requisiti.tex
> +\hline
```suggestion
\hline
RF05 & Obbligatorio & L'utente privilegiato deve poter visualizzare tutti i punti di interesse riconosciuti dal sistema. & Interna, UC1.2\\
\hline
```

2025-01-10 10:52 UTC, federicopivetta commented on RTB/Analisi_dei_Requisiti.tex
> +\hline
Vanno di conseguenza aggiornati gli altri requisiti funzionali e anche la tabella del tracciamento

2025-01-12 15:05 UTC, Aniysi commented on RTB/Analisi_dei_Requisiti.tex
> +RF15 & Obbligatorio & I dati validati dal sistema di Stream Processing devono essere elaborati tramite un servizio di LLM & Capitolato, UC8\\
```suggestion
RF15 & Obbligatorio & I dati validati dal sistema di Stream Processing devono essere elaborati tramite un servizio LLM & Capitolato, UC8\\

2025-01-13 07:59 UTC, Sadixo approved these changes

2025-01-14 09:44 UTC, federicopivetta commented on RTB/Analisi_dei_Requisiti.tex
> +      \item \textbf{Postcondizioni:} L'obiettivo è selezionare il punto di interesse (POI) più rilevante secondo gli interessi dell'utente. Il modello LLM utilizza le informazioni dei punti di intere
```suggestion
      \item \textbf{Postcondizioni:} L'obiettivo è selezionare il punto di interesse (POI) più rilevante secondo gli interessi dell'utente. Il modello LLM utilizza le informazioni dei punti di interesse (Tipologia) e dell'utente (Interessi) presenti all'interno del Database per fare una selezione tra i punti di interesse proposti.\\
```

2025-01-14 09:44 UTC, federicopivetta commented on RTB/Analisi_dei_Requisiti.tex
> + RF01 &  Obbligatorio &  L'utente privilegiato deve poter visualizzare la Dashboard$_G$ composta da una mappa interattiva con i vari marker e punti di interesse su di essa. &  Capitolato$_G$, UC1\\
```suggestion
 RF01 &  Obbligatorio &  L'utente privilegiato deve poter visualizzare la Dashboard$_G$ composta da una mappa interattiva con i vari marker su di essa. &  Capitolato$_G$, UC1\\
```

2025-01-14 09:44 UTC, federicopivetta commented on RTB/Analisi_dei_Requisiti.tex
> + RF01 &  Obbligatorio &  L'utente privilegiato deve poter visualizzare la Dashboard$_G$ composta da una mappa interattiva con i vari marker e punti di interesse su di essa. &  Capitolato$_G$, UC1\\
Così si evita di interpretare marker e PoI come entità distinte

2025-01-14 09:44 UTC, federicopivetta commented on RTB/Analisi_dei_Requisiti.tex
> +RF18 & Obbligatorio & Il servizio LLM deve essere in grado di selezionare il Punto di interesse più rilevante per l'utente in base alla profilazione e alla posizione in tempo reale & Capitolato, UC10
```suggestion
RF18 & Obbligatorio & Il servizio LLM deve essere in grado di selezionare il Punto di Interesse più rilevante per l'utente in base alle informazioni dei punti di interesse e dell'utente  & Capitolato, UC10\\
```

2025-01-14 09:44 UTC, federicopivetta commented on RTB/Analisi_dei_Requisiti.tex
> +RF19 & Obbligatorio & Il servizio LLM deve essere in grado di generare un messaggio custom per l'utente in base al suo profilo e al punto di interesse selezionato in tempo reale & Capitolato, UC11\\
```suggestion
RF19 & Obbligatorio & Il servizio LLM deve essere in grado di generare un messaggio custom per l'utente in base al suo profilo e alle informazioni del punto di interesse selezionato in tempo reale & Capitolato, UC11\\
```

2025-01-14 14:04 UTC, Meja04 requested changes

2025-01-14 14:04 UTC, Meja04 commented on RTB/Analisi_dei_Requisiti.tex
> +        \item Database
```suggestion
        \item Database;
```

2025-01-14 14:04 UTC, Meja04 commented on RTB/Analisi_dei_Requisiti.tex
> +        \item Sistema di Stream Processing
```suggestion
        \item Sistema di Stream Processing.
```

2025-02-06 14:52 UTC, Sadixo commented
@CodeUncas quando vuoi dai un'occhiata generale. Io ho finito di apportare le modifiche da fare in questo documento.

2025-02-06 16:59 UTC, CodeUncas reviewed
da sistemare la tabella finale , che va un po troppo sotto , forse da trasformare in long table, pagina 56 il numero va sopra la tabaella

2025-02-06 16:59 UTC, CodeUncas commented on RTB/Analisi_dei_Requisiti.tex
> +    \item \textbf{User-Story$_G$ associata:} Come utente privilegiato voglio visualizzare sulla mappa gli annunci pubblicitari che arrivano ai vari utenti.
```suggestion
    \item \textbf{User-Story$_G$ associata:} Come utente privilegiato voglio visualizzare sulla mappa gli annunci pubblicitari riservati ai vari utenti.
```

2025-02-06 16:59 UTC, CodeUncas commented on RTB/Analisi_dei_Requisiti.tex
> +     Come utente privilegiato voglio poter visualizzare un singolo annuncio generato dal sistema. Questa Dashboard$_G$ permette di tenere traccia del singolo annuncio, tramite un marker che rappresen
```suggestion
     Come utente privilegiato voglio poter visualizzare un singolo annuncio generato dal sistema. Questa Dashboard$_G$ permette di tenere traccia del singolo annuncio, tramite un marker che rappresenta la posizione in cui l'utente e il punto di interesse coinvolti sono presenti.
```

2025-02-06 16:59 UTC, CodeUncas commented on RTB/Analisi_dei_Requisiti.tex
> +Con l'intento di evitare ambiguità interpretative del linguaggio utilizzato, viene fornito un Glossario che si occupa di esplicitare il significato dei termini che riguardano il contesto del Progetto
```suggestion
Con l'intento di evitare ambiguità interpretative del linguaggio utilizzato, viene fornito un Glossario che si occupa di esplicitare il significato dei termini che riguardano il contesto del Progetto$_G$. I termini presenti nel glossario sono contrassegnati con una \textit{G} a pedice : Termine$_G$.\\
```

2025-02-06 16:59 UTC, CodeUncas commented on RTB/Analisi_dei_Requisiti.tex
> +Di seguito sono elencati gli attori con i quali si intefaccia il sistema:
```suggestion
Di seguito sono elencati gli attori con i quali si interfaccia il sistema:
```

2025-02-06 21:40 UTC, CodeUncas commented on RTB/Analisi_dei_Requisiti.tex
> +    \item [-] generazione e salvataggio di dati personali relativi a utenti fittizi, su cui dimostrare il funzionamento del software.
```suggestion
    \item [-] generazione e salvataggio di dati personali relativi a utenti fittizi, per dimostrare il funzionamento del software.
```

2025-02-06 21:40 UTC, CodeUncas commented on RTB/Analisi_dei_Requisiti.tex
> +Questa sezione espone una serie di Casi-d'uso$_G$ come risultato di un'Analisi-dei-Requisiti$_G$ continuativa del Capitolato$_G$, dal confronto con la Proponente$_G$ e dalle riflessioni degli Analisi
```suggestion
Questa sezione espone una serie di Casi-d'uso$_G$ come risultato di un'Analisi-dei-Requisiti$_G$ continuativa del Capitolato$_G$, dal confronto con la Proponente$_G$ e dalle riflessioni degli Analisti del team. La specifica di ogni Caso-d'uso$_G$ segue gli standard descritti in maniera dettagliata nel documento \textit{Norme$_G$\_di\_Progetto.pdf}.
```

2025-02-06 21:40 UTC, CodeUncas commented on RTB/Analisi_dei_Requisiti.tex
> +Questa sezione espone una serie di Casi-d'uso$_G$ come risultato di un'Analisi-dei-Requisiti$_G$ continuativa del Capitolato$_G$, dal confronto con la Proponente$_G$ e dalle riflessioni degli Analisi
```suggestion
Questa sezione espone una serie di Casi-d'uso$_G$ come risultato di un'Analisi-dei-Requisiti$_G$ continuativa del Capitolato$_G$, dal confronto con la Proponente$_G$ e dalle riflessioni degli Analisiti del team. La specifica di ogni Caso-d'uso$_G$ segue gli standard descritti in maniera dettagliata nel documento \textit{Norme$_G$\_di\_Progetto.pdf v1.0.0}.
```

2025-02-06 21:40 UTC, CodeUncas commented on RTB/Analisi_dei_Requisiti.tex
> +Le definizioni sono presenti nell'apposito documento \textit{Glossario.pdf}
```suggestion
Le definizioni sono presenti nell'apposito documento \textit{Glossario.pdf v1.0.0}
```

2025-02-08 14:16 UTC, Sadixo commented
Ho apportato le correzioni e inserito i G a pedice per i termini di vocabolario (compresi quelli nuovi). @CodeUncas se non trovi altro metti nel registro modifiche e nel file la V 1.0.0 e facciamo l'approvazione

2025-02-10 09:14 UTC, CodeUncas reviewed
altra verifica prima della chiusura della pr

2025-02-10 15:01 UTC, Meja04 approved these changes
Approvazione documento per RTB

2025-02-10 15:01 UTC, merged