Redazione iniziale del documento Norme di Progetto
SevenBitsSwe/7BitsDocs pull request #40
Opened 2024-11-21 09:13 UTC by federicopivetta

2024-11-22 17:58 UTC, federicopivetta commented
@riky869 ho messo te come Verificatore delle sezioni che ho aggiunto

2024-11-22 22:51 UTC, riky869 approved these changes
File visionati e corretti

2024-11-30 20:55 UTC, giocri approved these changes

2024-12-01 16:00 UTC, giocri approved these changes

2024-12-11 16:24 UTC, Sadixo commented on RTB/Norme_di_progetto.tex
> +        Misura quanto intuitivo, soddisfacente da usare e user-friendly è un software. Si compone di cinque sotto-caratteristiche:
```suggestion
        Misura quanto intuitivo, soddisfacente da usare e facile da usare è un software. Si compone di cinque sotto-caratteristiche:
```

2024-12-11 16:29 UTC, Sadixo commented on RTB/Norme_di_progetto.tex
> +        del sistema software che del suo uso delle risorse fisiche disponibili. Questo aspetto si puù ulteriormente dividere in tre sotto-caratteristiche:
```suggestion
        del sistema software che del suo uso delle risorse fisiche disponibili. Questo aspetto si può ulteriormente dividere in tre sotto-caratteristiche:
```

2024-12-15 16:24 UTC, Sadixo requested changes
@federicopivetta ho fatto alcune correzioni ortografiche e cambiamento di parole che secondo me non stavano bene. Attento a rispettare il tema della sottosezione in cui scrivi.

2024-12-15 16:24 UTC, Sadixo commented on RTB/Norme_di_progetto.tex
> +    Per garantire che ogni membro ricopra tutti i ruoli essenziali al completamento del progetto, il gruppo si impegna a ruotarli all'inizio di ogni nuovo sprint, della durata di due settimane.
```suggestion
    Per garantire che ogni membro ricopra tutti i ruoli essenziali al completamento del progetto, il gruppo si impegna a distribuirli all'inizio di ogni nuovo sprint, della durata di due settimane.
```
Vedi se trovi anche una parola più adatta

2024-12-15 16:24 UTC, Sadixo commented on RTB/Norme_di_progetto.tex
> +        Il preventivo delle ore è presentato sotto forma di tabella, che dettaglia le ore stimate per ogni membro del gruppo, suddivise per ruolo e riferite al singolo sprint. Inoltre, è incluso un d
```suggestion
        Il preventivo delle ore è presentato sotto forma di tabella, che dettaglia le ore stimate per ogni membro del gruppo, suddivise per ruolo e riferite al singolo sprint. Inoltre, è incluso un diagramma circolare che mostra la ripartizione delle ore stimate per ciascun ruolo, offrendo una visione chiara e immediata delle risorse che si pensa di allocare per quello specifico sprint.
```

2024-12-15 16:24 UTC, Sadixo commented on RTB/Norme_di_progetto.tex
> +        \item La issue viene associata alla milestone dello sprint attuale;
```suggestion
        \item La issue viene associata all'iterazione dello sprint attuale;  
```

2024-12-15 16:24 UTC, Sadixo commented on RTB/Norme_di_progetto.tex
> +        \item Il Verificatore esamina il lavoro svolto e comunica l’esito della verifica;
```suggestion
        \item Il Verificatore esamina il lavoro svolto e comunica l’esito della verifica tramite GitHub; 
```
Valuta se ha senso specificarlo o meno, perché così sembra che glielo si dica a voce

2024-12-15 16:24 UTC, Sadixo commented on RTB/Norme_di_progetto.tex
> +    La gestione dei rischi è un processo volto a identificare, valutare e affrontare le situazioni avverse che potrebbero influire sul successo del progetto. Questo approccio prevede l'individuazione
```suggestion
    La gestione dei rischi è un processo volto a identificare, valutare e affrontare le situazioni avverse che potrebbero influire sul successo del progetto. Questo approccio prevede l'individuazione dei rischi, la valutazione della loro gravità e occorrenza, la definizione di strategie per mitigarli ed, infine, un monitoraggio costante per rilevare la possibile comparsa di nuovi rischi.\\
```

2024-12-15 16:24 UTC, Sadixo commented on RTB/Norme_di_progetto.tex
> +    Questa attività comprende la gestione delle comunicazioni e degli incontri tra tutte le parti coinvolte nel progetto, inclusi i membri del gruppo, la proponente e i committenti.
```suggestion
    Questa attività comprende la gestione delle comunicazioni e degli incontri tra tutte le parti coinvolte nel progetto, che comprendono i membri del gruppo, la proponente e i committenti.
```
Vedi se inserire questa frase o come cambiarla

2024-12-15 16:24 UTC, Sadixo commented on RTB/Norme_di_progetto.tex
> +    Le comunicazioni sono fondamentali per mantenere un flusso costante di informazioni tra le parti coinvolte, garantendo efficienza e coordinamento nel progetto, e supportando il buon andamento del
```suggestion
    Le comunicazioni sono fondamentali per mantenere un flusso costante di informazioni tra le parti coinvolte, garantendo efficienza e coordinamento nel progetto, supportando il buon andamento delle attività e il raggiungimento degli obiettivi prefissati.\\ 
```

2024-12-15 16:24 UTC, Sadixo commented on RTB/Norme_di_progetto.tex
> +        Le comunicazioni esterne avverranno tramite scambio di email, utilizzando l'indirizzo sevenbits.swe.unipd@gmail.com. Questo canale sarà utilizzato per organizzare incontri con la proponente,
```suggestion
        Le comunicazioni interne avverranno attraverso due canali principali: Telegram e Discord. Telegram, un servizio di messaggistica istantanea, sarà utilizzato per le conversazioni rapide e informali, mentre Discord, una piattaforma che supporta chat e videochiamate, sarà impiegato per le riunioni a distanza e le discussioni più complesse.\\
        Le attività quotidiane e le comunicazioni generali si svolgeranno su Telegram, mentre le questioni critiche saranno affrontate durante degli incontri su Discord.
        
        \paragraph{Comunicazioni esterne}
        Le comunicazioni esterne avverranno tramite scambio di email, utilizzando l'indirizzo sevenbits.swe.unipd@gmail.com. Questo canale sarà utilizzato per organizzare incontri con la proponente, inviare documenti da visionare o firmare. Inoltre, su Discord è presente una sezione testuale dedicata alle comunicazioni rapide o dubbi con la proponente, nel loro apposito server Discord.
```
Dividere bene sezioni interne ed esterne

2024-12-15 16:24 UTC, Sadixo commented on RTB/Norme_di_progetto.tex
> +    Le riunioni sono fondamentali per il progresso del progetto, poiché offrono l'opportunità di confrontarsi, prendere decisioni e risolvere eventuali problematiche. Servono anche per monitorare lo
```suggestion
    Le riunioni sono fondamentali per il progresso del progetto, poiché offrono l'opportunità di confrontarsi, prendere decisioni e risolvere eventuali problematiche. Servono anche per monitorare lo stato di avanzamento delle attività e garantire il raggiungimento degli obiettivi prefissati.
```

2024-12-15 16:24 UTC, Sadixo commented on RTB/Norme_di_progetto.tex
> +        Le riunioni interne sono pianificate settimanalmente ogni mercoledì alle ore 16:00 o, in alternativa, subito dopo le riunioni esterne. In caso di necessità, possono essere richieste riunioni
```suggestion
        Le riunioni interne sono pianificate settimanalmente ogni mercoledì alle ore 16:00 o, in alternativa, subito dopo le riunioni esterne. In caso di necessità, possono essere richieste riunioni straordinarie durante la settimana, organizzate tramite un sondaggio sul canale Telegram. Tutte le riunioni si terranno sul canale Discord del gruppo. I membri del gruppo si impegnano a partecipare attivamente, cercando di garantire la loro presenza. In caso di impossibilità a partecipare, ogni membro potrà recuperare la sintesi delle discussioni e le decisioni prese leggendo il verbale della riunione.
```

2024-12-15 16:46 UTC, federicopivetta commented on RTB/Norme_di_progetto.tex
> +    Per garantire che ogni membro ricopra tutti i ruoli essenziali al completamento del progetto, il gruppo si impegna a ruotarli all'inizio di ogni nuovo sprint, della durata di due settimane.
Ho cambiato un po' la frase quindi appena carico le correzioni dagli un'occhiata

2024-12-15 16:58 UTC, federicopivetta commented
@Sadixo ho caricato le norme seguendo le correzioni

2024-12-16 15:09 UTC, Sadixo approved these changes

2024-12-19 17:59 UTC, Meja04 requested changes

2024-12-19 17:59 UTC, Meja04 commented on RTB/Norme_di_progetto.tex
> +    Effettuata sul prodotto software o sulla documentazione senza dover eseguire il sistema software. Serve ad accertare la conformità a regole adottate, l'assenza di difett e la presenza di propriet
```suggestion
    L'analisi statica è un tipo di analisi che viene effettuata sul prodotto software o sulla documentazione senza dover eseguire il sistema software. Serve ad accertare la conformità con le regole adottate, verificare l'assenza di difetti e la presenza di proprietà desiderate, garantendo un livello ottimale di qualità. Le due principali tecniche sono Inspection e Walkthrough. Il gruppo preferisce l'approccio ad Inspection, così da ridurre il tempo di verifica affinché l'autore possa dedicarsi alla stesura di altri documenti o codice.
```

2024-12-19 17:59 UTC, Meja04 commented on RTB/Norme_di_progetto.tex
> +    \subsubsection{Descrizione}
```suggestion
    \subsubsection{Descrizione e Scopo}
```

2024-12-19 17:59 UTC, Meja04 commented on RTB/Norme_di_progetto.tex
> +        \paragraph{Descrizione e scopo}
```suggestion
        \paragraph{Descrizione e Scopo} 
```

2024-12-19 17:59 UTC, Meja04 commented on RTB/Norme_di_progetto.tex
> +    La verifica è un processo essenziale che deve essere applicato a tutti gli altri processi per poterli considerare completati. Il suo scopo principale è quello di assicurarsi che i prodotti siano
```suggestion
    La verifica è un processo essenziale che deve essere applicato a tutti gli altri processi per poterli considerare completati. Il suo scopo principale è quello di assicurare che i prodotti siano corretti e che aderiscano ai vincoli individuati ed elencati nel documento \textit{Piano di Qualifica}. Le attività di verifica sono assegnate ai verificatori, che si impegnano a far rispettare i vincoli di qualità presenti nel \textit{Piano di Qualifica}, correggendo e/o segnalando qualora siano presenti contenuti non conformi agli standard.
```

2024-12-19 17:59 UTC, Meja04 commented on RTB/Norme_di_progetto.tex
> +    GitHub fornisce un servizio di review all'interno del meccanismo di PR, permettendo al verificatore di visualizzare le ultime modifiche. Il verificatore una volta verificato il documento può inse
```suggestion
    GitHub fornisce un servizio di review all'interno del meccanismo di PR, permettendo al verificatore di visualizzare le ultime modifiche. Il verificatore, una volta verificato il documento, può inserire commenti specifici contenenti correzioni o migliorie da apportare inviando una richiesta di modifica nella PR, oppure può approvare la PR e procedere con la verifica di altri prodotti presenti in repository in attesa di verifica. Una volta completata la verifica del documento, il verificatore può inserire commenti specifici con correzioni o suggerimenti per migliorie e inviare una richiesta di modifica nella Pull Request (PR). In alternativa, può approvare la PR e passare all'eventuale verifica di altri prodotti in attesa di revisione presenti nel repository. La review di GitHub consente all'intero team di poter tracciare le modifiche effettuate all'interno della repository.\\
```

2024-12-19 17:59 UTC, Meja04 commented on RTB/Norme_di_progetto.tex
> +    Il verificatore e l'autore del codice/documento da verificare discutono sulle modifiche da apportare. Questo processo richiede la presenza e la collaborazione di entrambi i ruoli.Viene effettuato
```suggestion
    Il verificatore e l'autore del prodotto da verificare discutono sulle modifiche da apportare. Questo processo richiede la presenza sincrona e la collaborazione di entrambi i ruoli, dunque risulta più complessa dell'Inspection in termini organizzativi. Viene effettuato un controllo ad ampio spettro dell'oggetto, senza avere un'idea precisa di cosa andare a verificare.
```

2024-12-19 17:59 UTC, Meja04 commented on RTB/Norme_di_progetto.tex
> +    Effettuata esclusivamente sul prodotto software tramite l'esecuzione effettiva di esso. L'analisi dinamica si divide in test. Ogni test è una esecuzione di un programma e provano il comportamento
```suggestion
     L'analisi dinamica viene condotta direttamente sul prodotto software attraverso la sua esecuzione effettiva. Questo tipo di analisi si suddivide in diverse tipologie di test, ciascuna finalizzata a verificare aspetti specifici del funzionamento del software. Ogni test corrisponde all'esecuzione di un programma, e simula il comportamento di singole parti di codice su un insieme finito di casi di prova.\\
```

2024-12-19 17:59 UTC, Meja04 commented on RTB/Norme_di_progetto.tex
> +    Questa procedura misura la qualità del prodotto e assicura che esegua correttamente il suo scopo. I test effettuati devono essere ripetibili nel tempo per assicurare funzionamento persistente dur
```suggestion
    Questa procedura misura la qualità del prodotto e assicura che esso raggiunga correttamente il suo scopo. I test effettuati devono essere ripetibili nel tempo per assicurare un funzionamento persistente durante tutto lo svolgimento del prodotto software.
```

2024-12-19 17:59 UTC, Meja04 commented on RTB/Norme_di_progetto.tex
> +    \item \textbf{Stato iniziale}: Parametri del software al momento dell'esecuzione del test;
```suggestion
    \item \textbf{Stato iniziale}: parametri del software al momento dell'esecuzione del test;
```

2024-12-19 17:59 UTC, Meja04 commented on RTB/Norme_di_progetto.tex
> +    \item \textbf{Output}: risultati attesi in uscita dato uno specifico input.
```suggestion
    \item \textbf{Output}: risultati attesi in uscita, dato uno specifico input.
```

2024-12-19 17:59 UTC, Meja04 commented on RTB/Norme_di_progetto.tex
> +    Inoltre i test sono divisi in varie categorie:
Toglierei la lista visto che dopo vengono descritti uno per paragrafo, così risulta coerente a come hai fatto prima per gli strumenti di verifica

2024-12-19 17:59 UTC, Meja04 commented on RTB/Norme_di_progetto.tex
> +    Test eseguiti su singole unità del software, come funzioni o metodi, in modo indipendente dal resto del sistema. L'obiettivo è assicurare che ogni unità di codice funzioni correttamente.Devono es
```suggestion
    Test eseguiti su singole unità del software, come funzioni o metodi, in modo indipendente dal resto del sistema. L'obiettivo è assicurare che ogni unità di codice funzioni correttamente. Devono essere eseguiti per primi visto che le unità garantiscono il corretto funzionamento dei singoli metodi che poi verranno integrati tra di loro.\\
```

2024-12-19 17:59 UTC, Meja04 commented on RTB/Norme_di_progetto.tex
> +    \item \textbf{Funzionale}: verificano che ogni unità esegue le funzione specificate nel design, facendo riferimento solo alla specifica input-output dell'oggetto di verifica;
```suggestion
    \item \textbf{Funzionale}: verificano che ogni unità esegua le funzioni specificate nel design, facendo riferimento solo alla specifica input-output dell'oggetto di verifica;
```

2024-12-19 17:59 UTC, Meja04 commented on RTB/Norme_di_progetto.tex
> +    L'obiettivo di questo test è di accertarsi che l'intero sistema lavori come entità unica, verificando che tutte le singole componenti funzionino insieme. Viene eseguita al completamento dei test
```suggestion
    L'obiettivo di questo test è di accertarsi che l'intero sistema lavori come entità unica, verificando che tutte le singole componenti funzionino insieme. Viene eseguito al completamento dei test di integrazione.
```

2024-12-19 17:59 UTC, Meja04 commented on RTB/Norme_di_progetto.tex
> +    Test da passare prima del rilascio del software. Serve a garantire che il prodotto finale soddisfi le aspettative del proponente e degli utenti finali.
```suggestion
    Sono gli ultimi test da passare prima del rilascio del software. Servono a garantire che il prodotto finale soddisfi le aspettative del proponente e degli utenti finali.
```

2024-12-19 17:59 UTC, Meja04 commented on RTB/Norme_di_progetto.tex
> +    Consiste nella ripetizione selettiva delle tipologie dei test elencati precedentemente e devono essere eseguiti ogni volta che si effettuano modifiche al codice.
```suggestion
    Consistono nella ripetizione selettiva delle tipologie dei test elencati precedentemente e devono essere eseguiti ogni volta che si effettuano modifiche al codice.
```

2024-12-19 17:59 UTC, Meja04 commented on RTB/Norme_di_progetto.tex
> +    I test vengono identificati in base alla loro tipologia e tramite un codice numerico, specifico all'interno della categoria. I test devono avere la seguente forma: \textbf{T[Tipologia Test][Codic
```suggestion
    I test vengono identificati in base alla loro tipologia e tramite un codice numerico, specifico all'interno della categoria. I test devono avere la seguente forma:  
    \begin{quote}
    \textbf{T[Tipologia][Codice]}
    \end{quote}\\
```

2024-12-19 17:59 UTC, Meja04 commented on RTB/Norme_di_progetto.tex
> +    Tipologia:
```suggestion
Dove:
                \item [-] \textbf{Tipologia}:
            \begin{itemize}
                \item [*] \textbf{U}: Unità;
                \item [*] \textbf{I}: Integrazione;
                \item [*] \textbf{S}: Sistema;
                \item [*] \textbf{A}: Accettazione;
            \end{itemize}
```

2024-12-19 17:59 UTC, Meja04 commented on RTB/Norme_di_progetto.tex
> +    \begin{itemize}
Lista da togliere se viene aggiunta sopra. Ho uniformato stilisticamente questa sezione come la 2.2.2.4

2024-12-27 10:21 UTC, Sadixo commented
@Meja04 ho apportato i cambiamenti che avevi chiesto settimana scorsa, se riesci ad approvare così si toglie l'icona dei cambiamenti richiesti.

2024-12-27 12:11 UTC, Meja04 approved these changes

2024-12-27 16:52 UTC, CodeUncas commented on RTB/Norme_di_progetto.tex
> +    Il suo scopo è quello di gestire e organizzare ogni modifica sul codice o sulla documentazione supportando con delle motivazioni alla base dei cambiamenti effettuati e con gli autori relativi
```suggestion
    Il suo scopo è quello di gestire e organizzare ogni modifica sul codice o sulla documentazione supportando con delle motivazioni alla base dei cambiamenti effettuati e con i relativi autori.
```

2024-12-27 16:54 UTC, CodeUncas commented
@federicopivetta sottosezione Gestione della configurazione verificata, indice di gulpease rispettato, ho proposto un piccolo cambiamento che rende la frase più naturale.

2024-12-27 17:01 UTC, CodeUncas commented on RTB/Norme_di_progetto.tex
> +fornire alle società di software un'approccio organizzato che faciliti e migliori la produzione di software e conseguentemente
```suggestion
fornire alle società di software un approccio organizzato che faciliti e migliori la produzione di software e conseguentemente 
```

2024-12-27 17:03 UTC, CodeUncas commented on RTB/Norme_di_progetto.tex
> +        Misura quanto il software soddisfa i requisiti funzionali espliciti e impliciti. Include cinque sotto-caratteristiche:
```suggestion
        Valuta quanto il software soddisfi i requisiti funzionali espliciti e impliciti. Include cinque sotto-caratteristiche:
```

2024-12-27 17:05 UTC, CodeUncas commented on RTB/Norme_di_progetto.tex
> +            \item Sicurezza - indica la capacità di un prodotto software di proteggere informazioni o dati, così che tutti coloro che interagiscono con tale prodotto (sia persone che altri
```suggestion
            \item Sicurezza - indica la capacità di un prodotto software di proteggere informazioni e dati, garantendo che tutti coloro che interagiscono con tale prodotto (sia persone che altri
```

2024-12-27 17:07 UTC, CodeUncas commented on RTB/Norme_di_progetto.tex
> +        \subsubsection{Usabilita}
```suggestion
        \subsubsection{Usabilità}
```

2024-12-27 17:09 UTC, CodeUncas commented on RTB/Norme_di_progetto.tex
> +        \subsubsection{Mnutenibilità}
```suggestion
        \subsubsection{Manutenibilità}
```

2024-12-27 17:22 UTC, CodeUncas commented
@Aniysi Verificato, tutto sommato i concetti ben definiti, qualche piccolo errore di accento, apostrofo, proposti i cambiamenti, indice di gulpease rispettato.

2025-01-04 11:02 UTC, CodeUncas commented on RTB/Norme_di_progetto.tex
> +                \item   \textbf{Descrizione}: metrica utilizzata usualmente per misurare la dimensione funzionale di un prodotto software. Si basa sulle funzionalità
```suggestion
                \item   \textbf{Descrizione}: metrica utilizzata per misurare la dimensione funzionale di un prodotto software. Si basa sulle funzionalità 
```

2025-01-04 11:04 UTC, CodeUncas commented on RTB/Norme_di_progetto.tex
> +    LO standard suddivide i processi in tre categorie principali che seguono la suddivisione effettuata in questo stesso documento:
```suggestion
    Lo standard suddivide i processi in tre categorie principali che seguono la suddivisione effettuata in questo stesso documento:
```

2025-01-04 11:04 UTC, CodeUncas commented on RTB/Norme_di_progetto.tex
> +    per tutta il corso del ciclo di vita di un prodotto software, dall'ideazione fino al ritiro.
```suggestion
    per tutto il corso del ciclo di vita di un prodotto software, dall'ideazione fino al ritiro.
```

2025-01-04 11:05 UTC, CodeUncas commented on RTB/Norme_di_progetto.tex
> +        le attività principali del ciclo di vita del software dalla concezione dello stesso fino alla sua realizzazione. Appartenenti a questa
```suggestion
        le attività principali del ciclo di vita del software, dalla concezione dello stesso fino alla sua realizzazione. Appartenenti a questa 
```

2025-01-04 11:06 UTC, CodeUncas commented on RTB/Norme_di_progetto.tex
> +        efficiente. Esempi concreti dki questi processi possono essere documentazione, gestione della configurazione, gestione della qualità,
```suggestion
        efficiente. Esempi concreti di questi processi possono essere documentazione, gestione della configurazione, gestione della qualità, 
```

2025-01-04 11:10 UTC, CodeUncas commented on RTB/Norme_di_progetto.tex
> +                \item Recuperabilità - rappresenta la capacita del software di ripristinare un livello adeguato di prestazioni e di recuperare dati rilevanti a seguito di un malfunzionamento;
```suggestion
                \item Recuperabilità - rappresenta la capacità del software di ripristinare un livello adeguato di prestazioni e di recuperare dati rilevanti a seguito di un malfunzionamento;
```

2025-01-04 11:16 UTC, CodeUncas commented
@Aniysi verificato , metriche rispettate, alcune imperfezioni ( ti ho proposto le modifiche )

2025-02-17 16:02 UTC, CodeUncas commented on RTB/Norme_di_progetto.tex
> +     La qualità viene assicurata tramite processi di verifica e validazione, che permettono di monitorare l'aderenza agli standard definiti. Una volta stabiliti i criteri qualitativi nel \textit{Pian
```suggestion
     La qualità viene assicurata tramite processi di verifica e validazione, che permettono di monitorare l'aderenza agli standard definiti. Una volta stabiliti i criteri qualitativi nel \textit{Piano\_di\_Qualifica}, il gruppo si impegna a seguire le best-practices per ogni fase del progetto, dai processi di sviluppo alla produzione degli artefatti. La responsabilità di garantire l'applicazione degli standard è delegata ai Verificatori, che certificano la conformità dei prodotti e dei processi agli obiettivi qualitativi.\\
```

2025-02-17 16:03 UTC, CodeUncas commented on RTB/Norme_di_progetto.tex
> +    La gestione della qualità è documentata nel \textit{Piano\_di\_Qualifica\_v1.0.0.pdf}, che definisce le metriche e le soglie accettabili per i vari processi e prodotti. Eventuali modifiche agli s
```suggestion
    La gestione della qualità è documentata nel \textit{Piano\_di\_Qualifica}, che definisce le metriche e le soglie accettabili per i vari processi e prodotti. Eventuali modifiche agli standard o agli strumenti vengono tracciate e aggiornate in modo continuo per garantire un processo di miglioramento costante.
```

2025-02-17 16:03 UTC, CodeUncas commented on RTB/Norme_di_progetto.tex
> +    Per monitorare e valutare la qualità, vengono utilizzate specifiche metriche, adattate ai diversi processi coinvolti. Queste metriche forniscono uno strumento oggettivo per analizzare il lavoro s
```suggestion
    Per monitorare e valutare la qualità, vengono utilizzate specifiche metriche, adattate ai diversi processi coinvolti. Queste metriche forniscono uno strumento oggettivo per analizzare il lavoro svolto e identificare eventuali criticità. Le metriche sono descritte nel dettaglio nel \textit{Piano\_di\_Qualifica} e includono:
```

2025-02-17 16:04 UTC, CodeUncas commented on RTB/Norme_di_progetto.tex
> +            \item Stesura e avanzamento del documento \textit{Piano\_di\_Progetto\_v1.0.0.pdf};
```suggestion
            \item Stesura e avanzamento del documento \textit{Piano\_di\_Progetto};
```

2025-02-17 16:04 UTC, CodeUncas commented on RTB/Norme_di_progetto.tex
> +            \item Stesura e avanzamento del documento \textit{Norme\_di\_Progetto\_v1.0.0.pdf}.
```suggestion
            \item Stesura e avanzamento del documento \textit{Norme\_di\_Progetto}.
```

2025-02-17 16:04 UTC, CodeUncas commented on RTB/Norme_di_progetto.tex
> +            \item Stesura del documento \textit{Analisi\_dei\_Requisiti\_v1.0.0.pdf};
```suggestion
            \item Stesura del documento \textit{Analisi\_dei\_Requisiti};
```

2025-02-17 16:05 UTC, CodeUncas commented on RTB/Norme_di_progetto.tex
> +            \item Stesura e avanzamento del documento \textit{Piano\_di\_Qualifica\_v1.0.0.pdf};
```suggestion
            \item Stesura e avanzamento del documento \textit{Piano\_di\_Qualifica};
```

2025-02-17 16:05 UTC, CodeUncas commented on RTB/Norme_di_progetto.tex
> +    Per tracciare il tempo impiegato nei diversi ruoli durante il progetto, viene utilizzato uno spreadsheet dedicato, disponibile su Google Drive. Al termine di ogni sprint, viene utilizzato per gen
```suggestion
    Per tracciare il tempo impiegato nei diversi ruoli durante il progetto, viene utilizzato uno spreadsheet dedicato, disponibile su Google Drive. Al termine di ogni sprint, viene utilizzato per generare il consuntivo dello sprint appena concluso e il preventivo di quello appena iniziato, infine il membro con il ruolo di Responsabile ha il compito di inserire questi elementi all'interno del documento \textit{Piano\_di\_Progetto}.
```

2025-02-17 16:07 UTC, CodeUncas commented on RTB/Norme_di_progetto.tex
> +    Nel \textit{Piano\_di\_Qualifica\_v1.0.0.pdf} ogni test viene seguito dal suo stato:
```suggestion
    Nel \textit{Piano\_di\_Qualifica} ogni test viene seguito dal suo stato:
```

2025-02-21 14:45 UTC, merged