Verifica VerbaleEsterno del 2024-12-12
SevenBitsSwe/7BitsDocs pull request #69
Opened 2024-12-13 10:44 UTC by federicopivetta

2024-12-13 11:00 UTC, Meja04 approved these changes

2024-12-13 11:11 UTC, Sadixo commented on RTB/Verbali/Esterni/VerbaleEsterno-2024-12-12.tex
> +                \item Dorigo Andrea;
```suggestion
                \item Dorigo Andrea.
```

2024-12-13 11:11 UTC, Sadixo commented on RTB/Verbali/Esterni/VerbaleEsterno-2024-12-12.tex
> +                    \item Trolese Leonardo;
```suggestion
                    \item Trolese Leonardo.
```

2024-12-13 11:12 UTC, Sadixo commented on RTB/Verbali/Esterni/VerbaleEsterno-2024-12-12.tex
> +Nel corso del meeting è stato esaminato il punto di avanzamento del gruppo nello sprint e sono state poste delle domande ai proponenti per alcuni chiarimenti.
```suggestion
Nel corso del meeting è stato esaminato il punto di avanzamento del gruppo nello sprint e sono state poste delle domande al proponente per alcuni chiarimenti.
```

2024-12-13 11:13 UTC, Sadixo commented on RTB/Verbali/Esterni/VerbaleEsterno-2024-12-12.tex
> +Le domande sottoposte sono le seguenti:
```suggestion
Sono state poste le seguenti domande:
```

2024-12-13 11:13 UTC, Sadixo commented on RTB/Verbali/Esterni/VerbaleEsterno-2024-12-12.tex
> +    \item Rimane confermato l'obbligo di raggiungere una copertura dei test pari o superiore all'80\%, mentre il raggiungimento del 100\% è considerato un valore aggiunto?
```suggestion
    \item Rimane confermato l'obbligo di raggiungere una copertura dei test pari o superiore all'80\%, mentre il raggiungimento del 100\% è considerato un valore ideale?
```

2024-12-13 11:14 UTC, Sadixo commented on RTB/Verbali/Esterni/VerbaleEsterno-2024-12-12.tex
> +    \item È appropriato utilizzare il metodo geodistance di ClickHouse per il calcolo della distanza tra i punti?
```suggestion
    \item È appropriato utilizzare il metodo geoDistance di ClickHouse per il calcolo della distanza tra i punti?
```

2024-12-13 11:15 UTC, Sadixo commented on RTB/Verbali/Esterni/VerbaleEsterno-2024-12-12.tex
> +Le risposte fornite sono le seguenti:
```suggestion
Le risposte fornite dal proponente sono le seguenti:
```

2024-12-13 11:15 UTC, Sadixo commented on RTB/Verbali/Esterni/VerbaleEsterno-2024-12-12.tex
> +    \item Si, viene confermato quanto specificato nel capitolato.
```suggestion
    \item Viene confermato quanto specificato nel capitolato.
```

2024-12-13 11:17 UTC, Sadixo commented on RTB/Verbali/Esterni/VerbaleEsterno-2024-12-12.tex
> +    \item Si è deciso di documentare la scelta del metodo geodistance di ClickHouse nell'Analisi dei Requisiti, specificandola come requisito prestazionale, in quanto influisce significativamente sul
```suggestion
    \item Si è deciso di documentare la scelta del metodo geoDistance di ClickHouse nell'Analisi dei Requisiti, specificandola come requisito prestazionale, in quanto influisce significativamente sulle performance del sistema.
```

2024-12-13 11:18 UTC, Sadixo commented on RTB/Verbali/Esterni/VerbaleEsterno-2024-12-12.tex
> +    \item Si è deciso di creare una tabella separata nel database al fine di mantenere lo storico dei dati posizionali.
```suggestion
    \item Si è deciso di creare una tabella separata nel database al fine di mantenere lo storico dei dati posizionali degli utenti.
```

2024-12-13 11:19 UTC, Sadixo requested changes
@federicopivetta per quanto riguarda il range dei punti di interesse loro li hanno suggeriti ma comunque è a nostra discrezione. Ovviamente deve essere sensata

2024-12-14 09:53 UTC, federicopivetta commented
@Meja04 e @Sadixo ho corretto il verbale seguendo le correzioni suggerite, se va bene passate alla approvazione

2024-12-15 13:35 UTC, Sadixo approved these changes

2024-12-17 19:13 UTC, merged